nginx:
    build: ./nginx
    mem_limit: 256m
    cpu_shares: 512
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./node
    mem_limit: 256m
    cpu_shares: 512
    links:
        - redis
        - mongo
    ports:
        - "8080"
    environment:
        - PORT=8080
node2:
    build: ./node
    mem_limit: 256m
    cpu_shares: 512
    links:
        - redis
        - mongo
    ports:
<<<<<<< HEAD
        - "8080"
    environment:
        - PORT=8080
=======
        - "8081"
    environment:
        - PORT=8081
>>>>>>> 5964c403a9bb83b1b64f48338649e4778c978f77
node3:
    build: ./node
    mem_limit: 256m
    cpu_shares: 512
    links:
        - redis
        - mongo
    ports:
<<<<<<< HEAD
        - "8080"
    environment:
        - PORT=8080
=======
        - "8082"
    environment:
        - PORT=8082
>>>>>>> 5964c403a9bb83b1b64f48338649e4778c978f77
redis:
    image: redis
    mem_limit: 256m
    cpu_shares: 512
    ports:
        - "6379"
mongo:
    image: mongo
    mem_limit: 256m
    cpu_shares: 512
    ports:
        - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
