nginx:
    build: ./nginx
    mem_limit: 256m
    cpu_shares: 512
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
consul:
  image: progrium/consul
  restart: always
  hostname: consul
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  command: "-server -bootstrap"
node1:
    build: ./node
    mem_limit: 256m
    cpu_shares: 512
    links:
        - redis
        - mongo
        - consul
    ports:
        - "8080"
    environment:
        - PORT=8080
node2:
    build: ./node
    mem_limit: 256m
    cpu_shares: 512
    links:
        - redis
        - mongo
        - consul
    ports:
        - "8080"
    environment:
        - PORT=8080
node3:
    build: ./node
    mem_limit: 256m
    cpu_shares: 512
    links:
        - redis
        - mongo
        - consul
    ports:
        - "8080"
    environment:
        - PORT=8080
redis:
    image: redis
    mem_limit: 256m
    cpu_shares: 512
    ports:
        - "6379"
mongo:
    image: mongo
    mem_limit: 256m
    cpu_shares: 512
    ports:
        - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
