consul:
    command: -server -bootstrap -advertise 10.0.2.15
    image: progrium/consul:latest
    ports:
        - "8300:8300"
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
registrator:
    command: -ip=10.0.2.15 consul://consul:8500
    image: gliderlabs/registrator:latest
    links:
        - consul
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
nginx:
    build: ./nginx
    mem_limit: 256m
    cpu_shares: 512
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    image: alleles/node
    mem_limit: 256m
    cpu_shares: 512
    links:
        - redis
        - mongo
    ports:
        - "8080"
    environment:
        - PORT=8080
node2:
    image: alleles/node
    mem_limit: 256m
    cpu_shares: 512
    links:
        - redis
        - mongo
    ports:
        - "8080"
    environment:
        - PORT=8080
node3:
    image: alleles/node
    mem_limit: 256m
    cpu_shares: 512
    links:
        - redis
        - mongo
    ports:
        - "8080"
    environment:
        - PORT=8080
redis:
    image: redis
    mem_limit: 256m
    cpu_shares: 512
    ports:
        - "6379"
mongo:
    image: mongo
    mem_limit: 256m
    cpu_shares: 512
    ports:
        - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
